//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int IDCuenta { get; set; }
        public Nullable<int> IDMesas { get; set; }
        public Nullable<int> IDMesoneros { get; set; }
        public string Reserva { get; set; }
        public Nullable<System.DateTime> Apertura { get; set; }
        public Nullable<System.DateTime> Cierre { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Propina { get; set; }
        public string Status { get; set; }
        public Nullable<int> IDComanda { get; set; }
        public string Comisionista { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<bool> Imprimir { get; set; }
        public Nullable<decimal> Cargo { get; set; }
        public Nullable<decimal> Monedero { get; set; }
        public Nullable<int> IDTurno { get; set; }
        public string FormaPago { get; set; }
    }
}
