//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        public int IDInsumos { get; set; }
        public int IDGrupos { get; set; }
        public string Descripcion { get; set; }
        public string UnidadMedida { get; set; }
        public decimal UltimoCosto { get; set; }
        public decimal CostoPromedio { get; set; }
        public decimal CostoImpuesto { get; set; }
        public decimal IVA { get; set; }
        public string Inventariable { get; set; }
    }
}
