//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInsumos
    {
        public int IDMasterInsumos { get; set; }
        public Nullable<int> IDInsumos { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    }
}
