//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int IDMenu { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
