//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int IDTurno { get; set; }
        public Nullable<System.DateTime> Apertura { get; set; }
        public Nullable<System.DateTime> Cerrar { get; set; }
        public string StatusTurno { get; set; }
        public Nullable<decimal> FondoInicial { get; set; }
        public Nullable<decimal> FondoFinal { get; set; }
    }
}
