//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IDCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Tipo_Facturacion { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CodPostal { get; set; }
        public string FolioFiscal { get; set; }
        public string rfc { get; set; }
        public string Curp { get; set; }
        public string Giro { get; set; }
        public string Poblacion { get; set; }
        public string Contacto { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Telefono4 { get; set; }
        public string Telefono5 { get; set; }
    }
}
