//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int IDComanda { get; set; }
        public Nullable<int> IDMesas { get; set; }
        public Nullable<decimal> TotalPrecio { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IDMesoneros { get; set; }
        public Nullable<int> IDTurno { get; set; }
    }
}
