//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroRolUsuario
    {
        public int IDMaestroRolUsuario { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDRol { get; set; }
    }
}
