//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterComanda
    {
        public int IDMasterComanda { get; set; }
        public Nullable<int> IDComanda { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public Nullable<decimal> Precio { get; set; }
    }
}
