//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterCierreCuenta
    {
        public int IDMasterCierreCuenta { get; set; }
        public int IDCuenta { get; set; }
        public int IDCierre { get; set; }
    }
}
