//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public int IDModulo { get; set; }
        public string Modulo1 { get; set; }
    }
}
