//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promociones
    {
        public int IDPromociones { get; set; }
        public string descripcion { get; set; }
        public string status { get; set; }
        public string tipopromocion { get; set; }
        public string lunesinicio { get; set; }
        public string lunesfin { get; set; }
        public Nullable<bool> aplicalunes { get; set; }
        public string lunesdiasalida { get; set; }
        public string martesinicio { get; set; }
        public string martesfin { get; set; }
        public Nullable<bool> aplicamartes { get; set; }
        public string martesdiasalida { get; set; }
        public string miercolesinicio { get; set; }
        public string miercolesfin { get; set; }
        public Nullable<bool> aplicamiercoles { get; set; }
        public string miercolesdiasalida { get; set; }
        public string juevesinicio { get; set; }
        public string juevesfin { get; set; }
        public Nullable<bool> aplicajueves { get; set; }
        public string juevesdiasalida { get; set; }
        public string viernesinicio { get; set; }
        public string viernesfin { get; set; }
        public Nullable<bool> aplicaviernes { get; set; }
        public string viernesdiasalida { get; set; }
        public string sabadoinicio { get; set; }
        public string sabadofin { get; set; }
        public Nullable<bool> aplicasabado { get; set; }
        public string domingoinicio { get; set; }
        public string sabadodiasalida { get; set; }
        public string domingofin { get; set; }
        public Nullable<bool> aplicadomingo { get; set; }
        public string domingodiasalida { get; set; }
        public Nullable<bool> visualizar { get; set; }
        public Nullable<decimal> Relacionuno { get; set; }
        public Nullable<decimal> Relaciondos { get; set; }
        public Nullable<bool> forzarporproducto { get; set; }
        public Nullable<int> IDMenu { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> IDTipoDescuento { get; set; }
    }
}
