//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioDomicilio
    {
        public int IDDomilicilio { get; set; }
        public int IDCliente { get; set; }
        public string Calle { get; set; }
        public string Direccion { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string Cruzamientos { get; set; }
        public string Cruzamientos2 { get; set; }
        public string Colonia { get; set; }
        public string Zona { get; set; }
        public string Referencia { get; set; }
        public string Ciudad { get; set; }
        public string Delegación { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CP { get; set; }
    }
}
